default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database:  <%= Rails.application.credentials.dig(:development,:database, :db_name) %>
  username: <%= Rails.application.credentials.dig(:development, :database, :db_username) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :db_password) %>
  host: <%= Rails.application.credentials.dig(:development, :database, :db_host) %>
  port: <%= Rails.application.credentials.dig(:development, :database, :db_port) %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: finances_test
  username: <%= Rails.application.credentials.dig(:development, :database, :db_username) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :db_password) %>

cable:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  channel_prefix: shared_finances_production

queue:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

cache:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

