default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database:  <%= Rails.application.credentials.development.dig(:database, :db_name) %>
  username: <%= Rails.application.credentials.development.dig(:database, :db_username) %>
  password: <%= Rails.application.credentials.development.dig(:database, :db_password) %>
  host: <%= Rails.application.credentials.development.dig(:database, :db_host) %>
  port: <%= Rails.application.credentials.development.dig(:database, :db_port) %>

production:
  <<: *default
  database:  <%= Rails.application.credentials.production.dig(:database, :db_name) %>
  username: <%= Rails.application.credentials.production.dig(:database, :db_username) %>
  password: <%= Rails.application.credentials.production.dig(:database, :db_password) %>
  host: <%= Rails.application.credentials.production.dig(:database, :db_host) %>
  port: <%= Rails.application.credentials.production.dig(:database, :db_port) %>

test:
  <<: *default
  database: finances_test
  username: admin
  password: 1234

