default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # Configuración para ActionCable en producción
  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database:  <%= Rails.application.credentials.dig(:development,:database, :db_name) %>
  username: <%= Rails.application.credentials.dig(:development, :database, :db_username) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :db_password) %>
  host: <%= Rails.application.credentials.dig(:development, :database, :db_host) %>
  port: <%= Rails.application.credentials.dig(:development, :database, :db_port) %>

production:
  <<: *default
  database:  <%= Rails.application.credentials.production.dig(:production, :database, :db_name) %>
  username: <%= Rails.application.credentials.production.dig(:production, :database, :db_username) %>
  password: <%= Rails.application.credentials.production.dig(:production, :database, :db_password) %>
  host: <%= Rails.application.credentials.production.dig(:production, :database, :db_host) %>
  port: <%= Rails.application.credentials.production.dig(:production, :database, :db_port) %>

test:
  <<: *default
  database: finances_test
  username: admin
  password: 1234

